### ISSUE TITLE
How use it?

### ISSUE THREAD

**Issue by 1072028371** [kingsamchen/KAdBlockEngine#1]
i don't know how to use it.
can you give me a total sample?
i want to learn rule engine in c++.

**Comment by kingsamchen** [comment]
Please checkout file at https://github.com/kingsamchen/KAdBlockEngine/blob/master/src/main.cpp, it provides a minimum test case(usage sample).

I'm afraid I can't provide any more detailed samples, which could be tedious. Just look at header files in folder src/adblock_engine, they should be self-documented.

**Comment by 1072028371** [comment]
Thanks so much for response.
